package com.caoping.cloud.db;

import android.database.sqlite.SQLiteDatabase;
import com.caoping.cloud.entiy.City;
import com.caoping.cloud.entiy.Member;
import com.caoping.cloud.entiy.ShoppingCart;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;

    private final CityDao cityDao;

    private final DaoConfig shoppingCartDaoConfig;

    private final ShoppingCartDao shoppingCartDao;

    private final DaoConfig memberDaoConfig;

    private final MemberDao memberDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);

        registerDao(City.class, cityDao);

        shoppingCartDaoConfig = daoConfigMap.get(ShoppingCartDao.class).clone();
        shoppingCartDaoConfig.initIdentityScope(type);

        shoppingCartDao = new ShoppingCartDao(shoppingCartDaoConfig, this);


        registerDao(ShoppingCart.class, shoppingCartDao);


        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        memberDao = new MemberDao(memberDaoConfig, this);

        registerDao(Member.class, memberDao);
    }
    
    public void clear() {
        cityDaoConfig.getIdentityScope().clear();
        shoppingCartDaoConfig.getIdentityScope().clear();
        memberDaoConfig.getIdentityScope().clear();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public ShoppingCartDao getShoppingCartDao() {
        return shoppingCartDao;
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

}
