package com.caoping.cloud.entiy;

import com.caoping.cloud.db.DaoSession;
import com.caoping.cloud.db.MemberDao;
import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MEMBER.
 */
public class Member {

    /** Not-null value. */
    private String empId;
    private String emp_number;
    private String empMobile;
    private String empPass;
    private String empName;
    private String empCover;
    private String empSex;
    private String isUse;
    private String dateline;
    private String emp_birthday;
    private String hxUsername;
    private String isInGroup;
    private String pushId;
    private String lat;
    private String lng;
    private String level_id;
    private String emp_erweima;
    private String emp_up;
    private String emp_up_mobile;
    private String levelName;
    private String jfcount;
    private String emp_pay_pass;
    private String package_money;
    private String empType;
    private String is_card_emp;
    private String lx_attribute_id;
    private String level_zhe;
    private String is_vip_one;
    private String is_vip_two;
    private String is_vip_three;
    private String is_vip_four;
    private String is_vip_five;
    private String is_shiming_rz;
    private String is_qiye_rz;
    private String company_id;
    private String company_name;
    private String company_person;
    private String company_tel;
    private String company_address;
    private String lat_company;
    private String lng_company;
    private String company_pic;
    private String is_check;
    private String provinceid;
    private String cityid;
    private String areaid;
    private String is_gys;
    private String is_fws;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MemberDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Member() {
    }

    public Member(String empId) {
        this.empId = empId;
    }

    public Member(String empId, String emp_number, String empMobile, String empPass, String empName, String empCover, String empSex, String isUse, String dateline, String emp_birthday, String hxUsername, String isInGroup, String pushId, String lat, String lng, String level_id, String emp_erweima, String emp_up, String emp_up_mobile, String levelName, String jfcount, String emp_pay_pass, String package_money, String empType, String is_card_emp, String lx_attribute_id, String level_zhe, String is_vip_one, String is_vip_two, String is_vip_three, String is_vip_four, String is_vip_five, String is_shiming_rz, String is_qiye_rz, String company_id, String company_name, String company_person, String company_tel, String company_address, String lat_company, String lng_company, String company_pic, String is_check, String provinceid, String cityid, String areaid, String is_gys, String is_fws) {
        this.empId = empId;
        this.emp_number = emp_number;
        this.empMobile = empMobile;
        this.empPass = empPass;
        this.empName = empName;
        this.empCover = empCover;
        this.empSex = empSex;
        this.isUse = isUse;
        this.dateline = dateline;
        this.emp_birthday = emp_birthday;
        this.hxUsername = hxUsername;
        this.isInGroup = isInGroup;
        this.pushId = pushId;
        this.lat = lat;
        this.lng = lng;
        this.level_id = level_id;
        this.emp_erweima = emp_erweima;
        this.emp_up = emp_up;
        this.emp_up_mobile = emp_up_mobile;
        this.levelName = levelName;
        this.jfcount = jfcount;
        this.emp_pay_pass = emp_pay_pass;
        this.package_money = package_money;
        this.empType = empType;
        this.is_card_emp = is_card_emp;
        this.lx_attribute_id = lx_attribute_id;
        this.level_zhe = level_zhe;
        this.is_vip_one = is_vip_one;
        this.is_vip_two = is_vip_two;
        this.is_vip_three = is_vip_three;
        this.is_vip_four = is_vip_four;
        this.is_vip_five = is_vip_five;
        this.is_shiming_rz = is_shiming_rz;
        this.is_qiye_rz = is_qiye_rz;
        this.company_id = company_id;
        this.company_name = company_name;
        this.company_person = company_person;
        this.company_tel = company_tel;
        this.company_address = company_address;
        this.lat_company = lat_company;
        this.lng_company = lng_company;
        this.company_pic = company_pic;
        this.is_check = is_check;
        this.provinceid = provinceid;
        this.cityid = cityid;
        this.areaid = areaid;
        this.is_gys = is_gys;
        this.is_fws = is_fws;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMemberDao() : null;
    }

    /** Not-null value. */
    public String getEmpId() {
        return empId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    public String getEmp_number() {
        return emp_number;
    }

    public void setEmp_number(String emp_number) {
        this.emp_number = emp_number;
    }

    public String getEmpMobile() {
        return empMobile;
    }

    public void setEmpMobile(String empMobile) {
        this.empMobile = empMobile;
    }

    public String getEmpPass() {
        return empPass;
    }

    public void setEmpPass(String empPass) {
        this.empPass = empPass;
    }

    public String getEmpName() {
        return empName;
    }

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public String getEmpCover() {
        return empCover;
    }

    public void setEmpCover(String empCover) {
        this.empCover = empCover;
    }

    public String getEmpSex() {
        return empSex;
    }

    public void setEmpSex(String empSex) {
        this.empSex = empSex;
    }

    public String getIsUse() {
        return isUse;
    }

    public void setIsUse(String isUse) {
        this.isUse = isUse;
    }

    public String getDateline() {
        return dateline;
    }

    public void setDateline(String dateline) {
        this.dateline = dateline;
    }

    public String getEmp_birthday() {
        return emp_birthday;
    }

    public void setEmp_birthday(String emp_birthday) {
        this.emp_birthday = emp_birthday;
    }

    public String getHxUsername() {
        return hxUsername;
    }

    public void setHxUsername(String hxUsername) {
        this.hxUsername = hxUsername;
    }

    public String getIsInGroup() {
        return isInGroup;
    }

    public void setIsInGroup(String isInGroup) {
        this.isInGroup = isInGroup;
    }

    public String getPushId() {
        return pushId;
    }

    public void setPushId(String pushId) {
        this.pushId = pushId;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getLevel_id() {
        return level_id;
    }

    public void setLevel_id(String level_id) {
        this.level_id = level_id;
    }

    public String getEmp_erweima() {
        return emp_erweima;
    }

    public void setEmp_erweima(String emp_erweima) {
        this.emp_erweima = emp_erweima;
    }

    public String getEmp_up() {
        return emp_up;
    }

    public void setEmp_up(String emp_up) {
        this.emp_up = emp_up;
    }

    public String getEmp_up_mobile() {
        return emp_up_mobile;
    }

    public void setEmp_up_mobile(String emp_up_mobile) {
        this.emp_up_mobile = emp_up_mobile;
    }

    public String getLevelName() {
        return levelName;
    }

    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    public String getJfcount() {
        return jfcount;
    }

    public void setJfcount(String jfcount) {
        this.jfcount = jfcount;
    }

    public String getEmp_pay_pass() {
        return emp_pay_pass;
    }

    public void setEmp_pay_pass(String emp_pay_pass) {
        this.emp_pay_pass = emp_pay_pass;
    }

    public String getPackage_money() {
        return package_money;
    }

    public void setPackage_money(String package_money) {
        this.package_money = package_money;
    }

    public String getEmpType() {
        return empType;
    }

    public void setEmpType(String empType) {
        this.empType = empType;
    }

    public String getIs_card_emp() {
        return is_card_emp;
    }

    public void setIs_card_emp(String is_card_emp) {
        this.is_card_emp = is_card_emp;
    }

    public String getLx_attribute_id() {
        return lx_attribute_id;
    }

    public void setLx_attribute_id(String lx_attribute_id) {
        this.lx_attribute_id = lx_attribute_id;
    }

    public String getLevel_zhe() {
        return level_zhe;
    }

    public void setLevel_zhe(String level_zhe) {
        this.level_zhe = level_zhe;
    }

    public String getIs_vip_one() {
        return is_vip_one;
    }

    public void setIs_vip_one(String is_vip_one) {
        this.is_vip_one = is_vip_one;
    }

    public String getIs_vip_two() {
        return is_vip_two;
    }

    public void setIs_vip_two(String is_vip_two) {
        this.is_vip_two = is_vip_two;
    }

    public String getIs_vip_three() {
        return is_vip_three;
    }

    public void setIs_vip_three(String is_vip_three) {
        this.is_vip_three = is_vip_three;
    }

    public String getIs_vip_four() {
        return is_vip_four;
    }

    public void setIs_vip_four(String is_vip_four) {
        this.is_vip_four = is_vip_four;
    }

    public String getIs_vip_five() {
        return is_vip_five;
    }

    public void setIs_vip_five(String is_vip_five) {
        this.is_vip_five = is_vip_five;
    }

    public String getIs_shiming_rz() {
        return is_shiming_rz;
    }

    public void setIs_shiming_rz(String is_shiming_rz) {
        this.is_shiming_rz = is_shiming_rz;
    }

    public String getIs_qiye_rz() {
        return is_qiye_rz;
    }

    public void setIs_qiye_rz(String is_qiye_rz) {
        this.is_qiye_rz = is_qiye_rz;
    }

    public String getCompany_id() {
        return company_id;
    }

    public void setCompany_id(String company_id) {
        this.company_id = company_id;
    }

    public String getCompany_name() {
        return company_name;
    }

    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    public String getCompany_person() {
        return company_person;
    }

    public void setCompany_person(String company_person) {
        this.company_person = company_person;
    }

    public String getCompany_tel() {
        return company_tel;
    }

    public void setCompany_tel(String company_tel) {
        this.company_tel = company_tel;
    }

    public String getCompany_address() {
        return company_address;
    }

    public void setCompany_address(String company_address) {
        this.company_address = company_address;
    }

    public String getLat_company() {
        return lat_company;
    }

    public void setLat_company(String lat_company) {
        this.lat_company = lat_company;
    }

    public String getLng_company() {
        return lng_company;
    }

    public void setLng_company(String lng_company) {
        this.lng_company = lng_company;
    }

    public String getCompany_pic() {
        return company_pic;
    }

    public void setCompany_pic(String company_pic) {
        this.company_pic = company_pic;
    }

    public String getIs_check() {
        return is_check;
    }

    public void setIs_check(String is_check) {
        this.is_check = is_check;
    }

    public String getProvinceid() {
        return provinceid;
    }

    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    public String getCityid() {
        return cityid;
    }

    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    public String getAreaid() {
        return areaid;
    }

    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    public String getIs_gys() {
        return is_gys;
    }

    public void setIs_gys(String is_gys) {
        this.is_gys = is_gys;
    }

    public String getIs_fws() {
        return is_fws;
    }

    public void setIs_fws(String is_fws) {
        this.is_fws = is_fws;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
